### PR TITLE
Added Relative Path To Accept Button

### LINKED ISSUE #50: Accept button in privacy policy
Accept button in privacy policy should link back to the homepage. Need to update link

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Added Relative Path To Accept  Button
Issue no: #50  

Close: #50    

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The CSS Section works well on different devices.

## Changes Made:

- Added meta information to improve SEO and rendering compatibility.
- Organized the HTML code for better readability.
- Provided explanations for each section.
- Detailed Description:
- Added New Photo
- Added Media Queries
- Added Favicon
- Added About Section 
- Added About Section Pictures
- Added Footer Section
- Update CSS Section
- Added Relative Path

- Added meta information for the character set, compatibility, and viewport settings to improve the rendering of the web page.
Organized the HTML code into sections (Header, Main, and Scripts) to improve code readability.
- Included comments and section headings for clarity.
- Removed the duplicate logo and navigation elements.
- Improved accessibility by adding ARIA labels for navigation buttons.
- Added explanations and comments for different sections of the code.

## Screenshots

Screenshot 2023-11-01 074725

### CODE REVIEW

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Check It Sir Its Done...

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor And also sir I want to enlarge this project length By adding a Backend to it Like Full Funtionlly Logistics Website...
I have a Plan for this Project, Do you have any Plans? Any Ideas Regarding The Project then I willl Work On these Issues...

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana Yes I do have planned backend for this . But what are your thoughts and plans on this?

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana Yes I do have planned backend for this . But what are your thoughts and plans on this?

@Aryankpoor 
- Adding Backend to track the product Services like when and where their product is right now..., Adding the Functionality on Track Button.
- On the Product Button You have to fill out a form regarding which product They want to deliver and also from where to where on which medium, on which service it comes under. After Completing All of these The User Have to pay the money in the medium according to their Country... In order to say that Adding Payment Integration.
- If You want you also add Your Own Product Regarding Your Availability.
- On the Main Home page You may add Your services Under Respective Sections like Air Ways, Water Ways, etc...
- Like these Many Of Ways are there to make the Webpage to be a Best Logistics Website...
- If You want I will make a proper video oF The website that how the Project Look Like After All Updates...
-

**Comment by Aryankpoor** [comment]
we cant accept money as we are not actually providing services

**Comment by Aryankpoor** [comment]
create a new issue on this we can talk about it there

**Pull request merged**
