### PR TITLE
Added Favicon

### LINKED ISSUE #16: Add Favicon  icon As per the Project Name
@Aryankpoor Assign this issue to me under Hacktoberfest

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Add Favicon
Issue no: #16 

Close: #16 

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The Favicon Section works well on different devices.

## Changes Made:

- Added meta information to improve SEO and rendering compatibility.
- Organized the HTML code for better readability.
- Provided explanations for each section.
- Detailed Description:
- Added New Photo
- Added Media Queries
- Added Favicon

- Added meta information for the character set, compatibility, and viewport settings to improve the rendering of the web page.
Organized the HTML code into sections (Header, Main, and Scripts) to improve code readability.
- Included comments and section headings for clarity.
- Removed the duplicate logo and navigation elements.
- Improved accessibility by adding ARIA labels for navigation buttons.
- Added explanations and comments for different sections of the code.

## Screenshots

cargo

### CODE REVIEW

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Check It Sir

**Comment by Aryankpoor** [comment]
The favicon looks good. Open PR if you want it to be added

**Comment by Aryankpoor** [comment]
@Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana

@Aryankpoor Sir message padhha karoo thhodaa , Merge the PR of #18 this one on;y 2 min i will raise PR for Favicon

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor Sir Check #18 and merge it that was the base section ,,,a lot section to add code was ready but due to merge conflicts iAm unable to Raise Other PR So please ADD/Merge #18

**Pull request closed without merging**
