### PR TITLE
Added New Homepage

### LINKED ISSUE #10: Create A new Home page For Transport Services
@Aryankpoor  Assign This Issue to me under Hcktoberfest

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Add New Homepage for Transport services

Issue no: #10 

Close: #10 

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The Home Section works well on different devices.

## Changes Made:

- Added meta information to improve SEO and rendering compatibility.
- Organized the HTML code for better readability.
- Provided explanations for each section.
- Detailed Description:

- Added meta information for the character set, compatibility, and viewport settings to improve the rendering of the web page.
Organized the HTML code into sections (Header, Main, and Scripts) to improve code readability.
- Included comments and section headings for clarity.
- Removed the duplicate logo and navigation elements.
- Improved accessibility by adding ARIA labels for navigation buttons.
- Added explanations and comments for different sections of the code.

## Screenshots

Screenshot 2023-10-29 001406

### CODE REVIEW

**Comment by Kapileswar-Moharana** [comment]
@Aryankpoor ?

**Comment by Aryankpoor** [comment]
I think there is a requirement for a better name than just order delivery

**Comment by Kapileswar-Moharana** [comment]
> I think there is a requirement for a better name than just order delivery

@Aryankpoor Say me or think about the name But first merge this

**Comment by Kapileswar-Moharana** [comment]
> I think there is a requirement for a better name than just order delivery

@Aryankpoor I will  update the name by next PR , Have a lot of work to do i am waiting for you only from 8pm

**Review by Aryankpoor — APPROVED** [review]

**Pull request merged**
